### ISSUE TITLE
Disconnected or no live stream after moment

### ISSUE THREAD

**Issue by tiimsvk** [avdeevsv91/mjsxj02hl_firmware#12]
what is it that the camera disconnects after a while or stops sending the live stream?
The modem is close, the camera is updated to version 1.4.1

camera settings:
![Clipboard02](https://user-images.githubusercontent.com/52893640/200504276-6289ae53-1067-4446-8c47-1999133d917a.jpg)

photo after about 5 minutes:
![Clipboard03](https://user-images.githubusercontent.com/52893640/200504452-f2c6c320-8e6d-4240-8e8d-6e6c1a702c32.jpg)

**Comment by kasitoru** [comment]
Roll back to version 1.3.1, this is a bug, the fix will be later.

**Comment by tiimsvk** [comment]
it worked better with this version.
1-2 weeks without problems, but as soon as there was a Wi-Fi failure, the camera does not want to connect again, a manual restart of the power supply is required

**Comment by kasitoru** [comment]
> what is it that the camera disconnects after a while or stops sending the live stream?

Try this version https://t.me/mjsxj02hl_firmware/6021
