### ISSUE TITLE
MQTT entity name starts with the device name in your config

### ISSUE THREAD

**Issue by TheBisk** [avdeevsv91/mjsxj02hl_firmware#14]
Hi Kasitoru, is it possibile to update the MQTT component on the firmware?

Logger: homeassistant.components.mqtt.mixins
Source: components/mqtt/mixins.py:1325
Integration: MQTT (documentation, issues)
First occurred: 09:12:26 (6801 occurrences)
Last logged: 17:59:09

MQTT entity name starts with the device name in your config {'device': {'identifiers': ['mjsxj02hl_giardinoipcam_023c3a866e0038c1ee70030a1c425b13230aac0c210829e3'], 'manufacturer': 'Xiaomi', 'model': 'Mi Home Security Camera 1080P (MJSXJ02HL)', 'name': 'mjsxj02hl_giardinoipcam', 'sw_version': '1.5.0', 'connections': []}, 'availability': [{'topic': 'mjsxj02hl/giardinoipcam/state', 'payload_available': 'online', 'payload_not_available': 'offline'}], 'availability_mode': 'all', 'name': 'mjsxj02hl_giardinoipcam_info_free_configs', 'unique_id': 'mjsxj02hl_giardinoipcam_023c3a866e0038c1ee70030a1c425b13230aac0c210829e3_info_free_configs', 'unit_of_measurement': 'byte(s)', 'enabled_by_default': False, 'state_topic': 'mjsxj02hl/giardinoipcam/info', 'value_template': Template<template=({{ value_json.free_configs }}) renders=0>, 'encoding': 'utf-8', 'force_update': False, 'qos': 0, 'payload_not_available': 'offline', 'payload_available': 'online'}, this is not expected. Please correct your configuration. The device name prefix will be stripped off the entity name and becomes '_info_free_configs'

Thank you.
Mi Home Security Camera 1080P (MJSXJ02HL)
by Xiaomi
Firmware: 1.5.0

**Comment by kasitoru** [comment]
Fixed in version [1.6.0](/kasitoru/mjsxj02hl_firmware/releases/tag/1.6.0).
