### ISSUE TITLE
Keep disconnecting from AP

### ISSUE THREAD

**Issue by R-3MY** [avdeevsv91/mjsxj02hl_firmware#16]
Hi,

I have successfully setup the camera but she keep disconnecting and reconnecting from my AP. (it's an AP for domotic only so without internet).

The web interface is really slow too.

Regards, Rémy.

**Comment by TheBisk** [comment]
Ciao,

Try to do this:
Go to autorun settings of the ipcam and set gateway ip address as parameter for watchdog script.
Like this example, in my case the router addess is:
![image](https://github.com/kasitoru/mjsxj02hl_firmware/assets/47088987/b93ab481-aedc-4c12-92fc-7edf6ba9971c)
