### ISSUE TITLE
How to update firmware?

### ISSUE THREAD

**Issue by TheBisk** [avdeevsv91/mjsxj02hl_firmware#5]
what procedure must be followed to update the cam's firmware?
Is it possible to upload the file "demo_hlc6.bin" directly from the web interface, or do we have to copy the file to the micro sd and then start the cam by pressing the reset button?

![image](https://user-images.githubusercontent.com/47088987/145021584-5dc7bca7-0e64-4009-b034-e9e8cfe8cdf9.png)

Thanks for your work!

**Comment by kasitoru** [comment]
Upload the update file via the web interface (the memory card must be inserted), then turn off the camera, press the reset button and turn on the power. White LED should light up.
