### ISSUE TITLE
I can't discover the WIFI point

### ISSUE THREAD

**Issue by abrahamfa** [avdeevsv91/mjsxj02hl_firmware#6]
Hello.

I am following the steps you have on your website and I am not getting any results.

I have installed the uboot, later I introduce the demo_hlc6.bin file of its latest version in the camera and wait for the white led to turn on. The camera finishes turning on but I can't find any Wi-Fi point to configure it.

After not having any results, I install the original firmware and follow all the steps again but I can never see the wifi point.

The only good result I get is when I install its version 1.0 and not always. Tried updating from web UI by loading demo_hlc6.bin file but got no results.

One last note: I have another problem: When I install the original firmware and scan the code for the camera to connect to the xiaomi application, the camera is not able to connect. I don't know if I've broken something.

Thank you.

**Comment by kasitoru** [comment]
- After flashing, make a factory reset (hold down the reset button when the device is turned on).
- For stock firmware, restore the config partition backup. If it is missing, then restore a [full backup](https://kasito.ru/wp-content/uploads/2021/03/mjsxj02hl_full-dump_4.0.5-0105.bin) using the [HiBurn](https://kasito.ru/proshivka-zagruzchika-ip-kamery-mjsxj02hl-s-pomoshhyu-usb/) program (see UPD1 information).

**Comment by abrahamfa** [comment]
Factory restored and updated with your firmware. Now working with Frigate!

Regards, and thank you very much.
