### ISSUE TITLE
binary_sensors unavailable after server reboot

### ISSUE THREAD

**Issue by TheBisk** [avdeevsv91/mjsxj02hl_firmware#7]
Hello,
every time I restart the server the binary sensors become unavailable. restarting the ipcam too, the sensors become available again. Is it related to MQTT?
I can do something to solve this issue. 
Iam using the latest version of the firmware v.1.3.1

thank you.

**Comment by kasitoru** [comment]
This is a known problem. Wait for the new firmware version.

**Comment by kasitoru** [comment]
Fixed in latest version.
