### ISSUE TITLE
Detection Human OFF wrong command

### ISSUE THREAD

**Issue by darkfuncat** [avdeevsv91/mjsxj02hl_firmware#8]
Hi,
Thanks for thos great formware !
This makes the camera very usable now.
A small bug still remains (on my 2 cameras) : when the Human Detetection is lost, the system still send the (wrong) command ON.
In another words, the system send "humanoid_detect_exec" command instead of "humanoid_lost_exec".
Can you confirm this ? And perhaps fix or tell me how to fix ?

Edit :
Wrong diagnostic from me. It appears that the bug send a false "humanoid_detect_exec" short time after another "humanoid_detect_exec".
And sometimes it never returns "humanoid_lost_exec"... strange and still anoying.

Thanks

**Comment by kasitoru** [comment]
Try this version https://t.me/mjsxj02hl_firmware/6021

**Comment by darkfuncat** [comment]
Thanks, I will give it a try sooner.
But I see that the project is no longuer maintened and now use OpenIPC.
OpenIPC does not seem to have MQTT features, that's right ?

**Comment by kasitoru** [comment]
> OpenIPC does not seem to have MQTT features, that's right ?

All questions about the OpenIPC on this camera are asked here https://github.com/OpenIPC/device-mjsxj02hl/issues
