### ISSUE TITLE
Problem after flashing

### ISSUE THREAD

**Issue by Mattrees007** [avdeevsv91/mjsxj02hl_firmware#9]
I believe iv flashed the camera correctly.

The camera boots and produces a wifi hot spot "MJSXJ02HL".

When i try to connect to the hot spot, nothing progresses.

any ideas?

**Comment by Mattrees007** [comment]
i have now got passed this problem and joined the camera to my network but im now presented with a Busybox login screen. is there a default username and password?

**Comment by kasitoru** [comment]
> When i try to connect to the hot spot, nothing progresses

Set the network parameters manually:
```
IP address: 192.168.1.10
Subnet mask: 255.255.255.0
Primary Gateway: 192.168.1.1
```
>  default username and password

`root / toor`

**Comment by Mattrees007** [comment]
Many Thanks

Im in.

Great work!
